sudo: false
language: python
python:
    - "3.6"
install: pip install .
script:
    - mv config/rizza.yaml.example ~/rizza/config/rizza.yaml
    - mv config/server_configs.json.example ~/rizza/config/server_configs.json
    - pytest
