sudo: false
language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
install: pip install .
script:
    - mv config/rizza.yaml.example config/rizza.yaml
    - mv config/server_configs.json.example config/server_configs.json
    - pytest
