name: "Quality Checks"

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "*.md"
      - "*.rst"
      - ".gitignore"

jobs:
  pre_commit_checks:
    name: "Pre-Commit Checks"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python 3.13
        uses: actions/setup-python@v2
        with:
          python-version: "3.13"

      - name: Run Pre-Commit Hooks
        uses: pre-commit/action@v3.0.1

  python_tests:
    name: "Python Tests"
    runs-on: ubuntu-latest
    needs: pre_commit_checks
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # The "Pre Commit Checks" step has been moved to the 'pre_commit_checks' job

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Unit Tests
        env:
          UV_SYSTEM_PYTHON: 1
        run: |
          uv pip install "rizza @ ."
          rizza --help
          # mv config/rizza.yaml.example ~/rizza/config/rizza.yaml
          # mv config/server_configs.json.example ~/rizza/config/server_configs.json
          # pytest -v tests/
