name: "Quality Checks"

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "*.md"
      - "*.rst"
      - ".gitignore"

jobs:
  analyze:
    name: CodeQL Analysis
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Pre Commit Checks
        uses: pre-commit/action@v3.0.1

      - name: Unit Tests
        run: |
          pip install -U pip
          pip install .[dev]
          # mv config/rizza.yaml.example ~/rizza/config/rizza.yaml
          # mv config/server_configs.json.example ~/rizza/config/server_configs.json
          # pytest -v tests/
